title: "Documentação do AIOS"
remote_theme: just-the-docs/just-the-docs

# Configurações do Just the Docs
aux_links:
  "Repositório GitHub":
    - https://github.com/rigues/rigues.github.io

# Plugins necessários
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
