title: "Documentação do AIOS"
remote_theme: just-the-docs/just-the-docs

# Configurações do Just the Docs
aux_links:
  "Site da dtLabs":
    - https://www.dt-labs.ai

# Enable the navbar
nav_enabled: true

# Enable Heading Anchors
heading_anchors: true

# Plugins necessários
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
