title: "Documentação do AIOS"
remote_theme: just-the-docs/just-the-docs

markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown (suporta tabelas, tarefas, etc.)
  syntax_highlighter: rouge
  toc_levels: 2..3

# Configurações do Just the Docs
aux_links:
  "Site da dtLabs":
    - https://www.dt-labs.ai

# Enable the navbar
nav_enabled: true

# Enable Heading Anchors
heading_anchors: true

# Plugins necessários
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Extensões para Callouts
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Novo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red
